name: ChunkRandomizer
version: '${project.version}'
main: we.miners.chunkrandomizer.ChunkRandomizer
api-version: '1.20'
author: [ José Matos, Gil Monteiro ]
description: A plugin that randomizes the behaviour of chunks.
commands:
    chunkrandomizer:
        description: Main command of the plugin.
        usage: /<command> <subcommand> [args]
        aliases: [cr]
        permission: chunkrandomizer.command
        permission-message: You don't have permission to use this command.
        subcommands:
        start:
            description: Starts the randomization of chunks.
            usage: /<command> start
            permission: chunkrandomizer.command.start
            permission-message: You don't have permission to use this command.
        stop:
            description: Stops the randomization of chunks.
            usage: /<command> stop
            permission: chunkrandomizer.command.stop
            permission-message: You don't have permission to use this command.
        reload:
            description: Reloads the plugin configuration.
            usage: /<command> reload
            permission: chunkrandomizer.command.reload
            permission-message: You don't have permission to use this command.
        set:
            description: Sets the behaviour of a chunk.
            usage: /<command> set <chunk> <behaviour>
            permission: chunkrandomizer.command.set
            permission-message: You don't have permission to use this command.
        get:
            description: Gets the behaviour of a chunk.
            usage: /<command> get <chunk>
            permission: chunkrandomizer.command.get
            permission-message: You don't have permission to use this command.
        list:
            description: Lists all chunks with their behaviour.
            usage: /<command> list
            permission: chunkrandomizer.command.list
            permission-message: You don't have permission to use this command.